[Settings]
instance=SHARED
period=60

[SHARED]
hostname=hostname_shared
tenantId=actual_tenant_id_shared
userName=actual_username_shared_encrypted
token=-init-
; actual_personal_access_encrypted_token_customer1. init => request user to provide the token

[CUSTOMER1]
hostname=hostname_customer1
tenantId=actual_tenant_id_customer1
userName=actual_username_customer1_encrypted
token=-init-
; actual_personal_access_encrypted_token_customer1. init => request user to provide the token
